version: '3'
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: webservice_sb
    ports:
      - "9088:80"
    volumes:
      - ./back-end:/var/www/html
      - ./default_nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel
  php:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  front-end:
    build: 
      context: ./front-end
      dockerfile: Dockerfile 
    volumes:
      - ./front-end/src:/app/src  
      - ./front-end/public:/app/public  
    ports:
      - 4000:3000  
    expose:
      - '4000' 
